# Project information
site_name: 'Canine Glioma Project &middot; Verhaak Lab'
site_url: 'https://canineglioma.verhaaklab.com'
site_author: 'Samir B. Amin'
site_description: 'Canine Glioma Project &middot; Extended Methods, Data, and Code for Figures'

# Repository
repo_name: 'TheJacksonLaboratory/canineglioma'
repo_url: 'https://github.com/TheJacksonLaboratory/canineglioma'
edit_uri: ""

# Copyright
copyright: >-
  <a href="https://verhaaklab.com/privacy/">Disclosure</a>

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/fixed/favicon.png

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - navigation.tabs
    - navigation.instant
    - navigation.top
    - navigation.indexes
    - navigation.sections
    - content.code.annotate
  palette: #
    - scheme: default
      primary: blue
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate # 
      primary: teal
      accent: "light green"
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode
  font:
    text: 'Roboto'
    code: 'Fira Code'
  icon:
    logo: logo
    repo: material/github
  favicon: assets/images/fixed/favicon.png

# Plugins
plugins:
  - search
  - macros
  - git-revision-date-localized:
      type: iso_date
      timezone: 'America/New_York'
      fallback_to_build_date: true
  - minify:
      minify_html: true

## Customization
extra_css:
  - assets/css/extra.css

extra_javascript:
  - 'assets/js/extra.js'
  - 'assets/js/mathjax.js'
  - 'https://polyfill.io/v3/polyfill.min.js?features=es6'
  - 'https://cdn.jsdelivr.net/npm/mathjax@3/es5/tex-mml-chtml.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js'
  - 'assets/js/tables.js'

extra:
  disqus: ''
  twitter: 'sbamin'
  social:
    - icon: fontawesome/regular/envelope
      link: 'https://verhaaklab.com/contact'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/roelverhaak'
    - icon: fontawesome/brands/github
      link: 'https://github.com/sbamin'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/sbamin'
  repo:
    url: https://github.com/TheJacksonLaboratory/canineglioma
    tree: /tree/main
    blob: /blob/main
  analytics:
    provider: google
    property: UA-64053990-2
  site_keywords: "canine,glioma,pediatric,comparative genomics,DIPG,verhaak,lab,jax"
  version:
    provider: mike
    default: latest
  twittercard:
    user: roelverhaak
    logourl: '/assets/images/lab_logo_sq-md.jpg'  

# Extensions
markdown_extensions:
  - admonition
  - abbr
  - attr_list
  - def_list
  - footnotes
  - meta
  - md_in_html
  - toc:
      permalink: true
  - pymdownx.arithmatex:
      generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      social_url_shortener: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: sbamin
      repo: code101
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed:
      alternate_style: true
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde

# Page tree
nav:
    - Home: index.md
    - Methods:
      - Samples: methods/S01_samples.md
      - Data Sources: methods/S02_data_sources.md
      - Sample Preparations: methods/S03_sample_prep.md
      - Alignments: methods/S04_alignments_fprint.md
      - Somatic SNVs and Indels: methods/S05_somatic_variants.md
      - Significantly Mutated Genes: methods/S06_smgs.md
      - Cancer Hallmarks: methods/S07_hallmarks.md
      - Somatic Mutation Rate: methods/S09_mutation_rate.md
      - Somatic Copy Number Aberrations: methods/S10_SCNA.md
      - Aneuploidy Metrics: methods/S11_aneuploidy.md
      - Intratumor Heterogeneity: methods/S12_ith.md
      - Mutational Signatures: methods/S13_mut_sigs.md
      - Molecular Timing of Somatic Drivers: methods/S14_mut_timing.md
      - Class Prediction using methylation classifier: methods/S15_class_predict_methy.md
      - Immune Microenvironment Analysis: methods/S16_expression_immune.md
    - Figures:
      - Start Here: figures/A1_preload.md
      - F1:
        - figures/F1A.md
        - figures/F1B.md
        - figures/F1C.md
        - figures/F1D.md
        - figures/S1.md
      - F2:
        - figures/F2A.md
        - figures/F2B.md
        - figures/F2C.md
        - figures/F2D.md
        - figures/S2.md
      - F3:
        - figures/F3A.md
        - figures/F3B.md
        - figures/F3C.md
        - figures/F3D.md
        - figures/S3.md
      - F4:
        - figures/F4.md
        - figures/S4.md
      - F5:
        - figures/F5.md
        - figures/S5.md
    - R Markdown:
        - How-To: run_code/index.md
        - Output: run_code/run_all.md
    - Contact: https://verhaaklab.com/contact
