# Copyright (c) 2016-2020 Martin Donath <martin.donath@squidfunk.com>

# Permission is hereby granted, free of charge, to any person obtaining a copy
# of this software and associated documentation files (the "Software"), to
# deal in the Software without restriction, including without limitation the
# rights to use, copy, modify, merge, publish, distribute, sublicense, and/or
# sell copies of the Software, and to permit persons to whom the Software is
# furnished to do so, subject to the following conditions:

# The above copyright notice and this permission notice shall be included in
# all copies or substantial portions of the Software.

# THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR
# IMPLIED, INCLUDING BUT NOT LIMITED TO THE WARRANTIES OF MERCHANTABILITY,
# FITNESS FOR A PARTICULAR PURPOSE AND NON-INFRINGEMENT. IN NO EVENT SHALL THE
# AUTHORS OR COPYRIGHT HOLDERS BE LIABLE FOR ANY CLAIM, DAMAGES OR OTHER
# LIABILITY, WHETHER IN AN ACTION OF CONTRACT, TORT OR OTHERWISE, ARISING
# FROM, OUT OF OR IN CONNECTION WITH THE SOFTWARE OR THE USE OR OTHER DEALINGS
# IN THE SOFTWARE.

# Site details
site_name: 'Canine Glioma Project &middot; Verhaak Lab'
site_description: 'Canine Glioma Project &middot; Extended Methods, Data, and Code for Figures'
site_keywords: "canine,glioma,pediatric,comparative genomics,DIPG,verhaak,lab,jax"
site_author: 'Samir B. Amin'
site_url: 'https://canineglioma.verhaaklab.com'
## enable 'edit this page' link
repo_edit: false
repo_name: 'TheJacksonLaboratory/canineglioma'
repo_url: 'https://github.com/TheJacksonLaboratory/canineglioma'
## add last modified, require git-revision-date-localized plugin
last_modtime: true
copyright: 'Copyright &copy; 2017 - 2021 <a href="https://verhaaklab.com">Verhaak Lab at the Jackson Laboratory for Genomic Medicine</a>'

# Configuration
theme:
  name: material
  custom_dir: overrides
  logo: assets/images/logo.png

  # 404 page
  static_templates:
    - 404.html

  # Don't include MkDocs' JavaScript
  include_search_page: false
  search_index_only: true

  # Default values, taken from mkdocs_theme.yml
  language: en
  features:
    - tabs
    - instant
    - search.suggest
    - search.highlight
    - search.share
  palette:
    primary: blue
    accent: indigo
  font:
    text: 'IBM Plex Sans'
    code: 'Fira Code'
  icon:
    logo: logo
  favicon: /assets/images/logo.png

# Plugins
plugins:
  - search:
      separator: '[\s\-\.]+'
  - git-revision-date-localized:
      type: date
      fallback_to_build_date: true
  - minify:
      minify_html: true

# Google Analytics
google_analytics:
  # - !!python/object/apply:os.getenv ["UA-64053990-1"]
  - UA-64053990-2
  - auto

# Customization
extra_css:
  - /assets/css/extra.css
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.css'

extra_javascript:
  - '/assets/js/extra.js'
  - '/assets/js/katex.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/katex.min.js'
  - 'https://cdn.jsdelivr.net/npm/katex@0.11.1/dist/contrib/auto-render.min.js'
  - 'https://cdnjs.cloudflare.com/ajax/libs/tablesort/5.2.1/tablesort.min.js'
  - '/assets/js/tables.js'

extra:
  disqus: 'verhaaklab'
  social:
    - icon: fontawesome/regular/envelope
      link: 'https://verhaaklab.com/contact'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/roelverhaak'
    - icon: fontawesome/brands/github
      link: 'https://github.com/sbamin'
    - icon: fontawesome/brands/twitter
      link: 'https://twitter.com/sbamin'
  twittercard:
    user: roelverhaak
    logourl: '/assets/images/lab_logo_sq-md.jpg'

# Google Analytics
google_analytics:
  - 'UA-64053990-2'
  - 'auto'

# Extensions
markdown_extensions:
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.codehilite:
      guess_lang: false
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta
  - markdown.extensions.toc:
      permalink: true
  # - pymdownx.arithmatex
  #     generic: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.caret
  - pymdownx.critic
  - pymdownx.details
  - pymdownx.emoji:
      emoji_index: !!python/name:materialx.emoji.twemoji
      emoji_generator: !!python/name:materialx.emoji.to_svg
  - pymdownx.highlight:
      use_pygments: true
      linenums: false
      linenums_style: pymdownx-inline
  - pymdownx.inlinehilite
  - pymdownx.keys
  - pymdownx.magiclink:
      social_url_shortener: true
      repo_url_shortener: true
      repo_url_shorthand: true
      user: sbamin
      repo: issueboard
  - pymdownx.mark
  - pymdownx.smartsymbols
  - pymdownx.snippets:
      check_paths: true
  - pymdownx.superfences
  - pymdownx.tabbed
  - pymdownx.tasklist:
      custom_checkbox: true
      clickable_checkbox: true
  - pymdownx.tilde
  - meta

# Pages
nav:
    - Home: index.md
    - Methods:
      - Samples: methods/S01_samples.md
      - Data Sources: methods/S02_data_sources.md
      - Sample Preparations: methods/S03_sample_prep.md
      - Alignments: methods/S04_alignments_fprint.md
      - Somatic SNVs and Indels: methods/S05_somatic_variants.md
      - Significantly Mutated Genes: methods/S06_smgs.md
      - Cancer Hallmarks: methods/S07_hallmarks.md
      - Somatic Mutation Rate: methods/S09_mutation_rate.md
      - Somatic Copy Number Aberrations: methods/S10_SCNA.md
      - Aneuploidy Metrics: methods/S11_aneuploidy.md
      - Intratumor Heterogeneity: methods/S12_ith.md
      - Mutational Signatures: methods/S13_mut_sigs.md
      - Molecular Timing of Somatic Drivers: methods/S14_mut_timing.md
      - Class Prediction using methylation classifier: methods/S15_class_predict_methy.md
      - Immune Microenvironment Analysis: methods/S16_expression_immune.md
    - Figures:
      - Start Here: figures/A1_preload.md
      - F1:
        - figures/F1A.md
        - figures/F1B.md
        - figures/F1C.md
        - figures/F1D.md
        - figures/S1.md
      - F2:
        - figures/F2A.md
        - figures/F2B.md
        - figures/F2C.md
        - figures/F2D.md
        - figures/S2.md
      - F3:
        - figures/F3A.md
        - figures/F3B.md
        - figures/F3C.md
        - figures/F3D.md
        - figures/S3.md
      - F4:
        - figures/F4.md
        - figures/S4.md
      - F5:
        - figures/F5.md
        - figures/S5.md
    - R Markdown:
        - How-To: run_code/index.md
        - Output: run_code/run_all.md
    - Contact: https://verhaaklab.com/contact
